spring:

  r2dbc:
    username: postgres
    password: postgres
    url: r2dbc:postgresql://localhost:5432/postgres

  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres